# Generated by Django 3.1.1 on 2020-09-28 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_type', models.CharField(choices=[('SS', 'Shared Server'), ('PS', 'Private Server'), ('TS', 'Test Server')], max_length=50)),
                ('server_flavor', models.CharField(choices=[('C2_4GB', '2c 4GB'), ('C4_8GB', '4c 8Gb'), ('C4_16GB', '4c 16Gb'), ('C8_32Gb', '8c 32Gb'), ('C8_64GB', '8c 64Gb')], max_length=50)),
                ('server_status', models.CharField(choices=[('IN_PROGRESS', 'A command is being processed'), ('RUNNING', 'VM up and running'), ('STOPPED', 'VM is stopped'), ('DELETED', 'VM deleted')], max_length=50)),
                ('server_storage', models.CharField(choices=[('TB10', '10 Tb'), ('TB50', '50 Tb'), ('TB100', '100 Tb')], max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('command', models.CharField(choices=[('CREATE', 'create'), ('CLONE', 'clone'), ('MODIFY', 'modify'), ('STOP', 'stop'), ('START', 'start'), ('DELETE', 'delete')], max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commands', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_commands', to='servers.server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
